TodoLegal/TodoLegal

- app/views/devise/registrations/new.html.erb
- app/views/home/drive_search.html.erb
- app/views/layouts/_logged_navbar.html.erb
- app/views/layouts/_unlogged_navbar.html.erb
- public/css/law_view.css
- public/css/new_theme.css
Ajustes de estilos en Navigation bar, Search bar del home, Y labels en el form de onboarding.
> Ui fixes contrast

- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/home/invite_friends.html.erb
- app/views/home/privacy_policy.html.erb
- app/views/home/terms_and_conditions.html.erb
- app/views/layouts/_footer.html.erb
- app/views/layouts/_unlogged_navbar.html.erb
- public/404.html
- public/500.html
- public/css/law_view.css
- public/css/new_theme.css
- public/maintenance.html
Changes to adjust font, button, input sizes, margins and paddings.
> Ui sizes optimization

- app/views/home/_search_law_input.html.erb
- public/css/footer.css
- public/css/new_theme.css
CSS changes to include position absolute and various adjustments on helpcard & search
> Added styles to adjust HelpCard on Search

- app/views/devise/sessions/new.html.erb
- app/views/home/pricing.html.erb
- public/css/new_theme.css
Styles are up to date with the last version.
> Added new styles for pricing pages

- app/views/billing/checkout.html.erb
- app/views/home/pricing.html.erb
- public/css/new_theme.css
Additional content and commented content that should be displayed after Aug 17.
> Added new changes for 50% discount in Checkout and pricing

- app/views/home/_search_result.html.erb
- app/views/home/drive_search.html.erb
- app/views/home/pricing.html.erb
- app/views/home/search_law.html.erb
- app/views/laws/_navbar_subbar.html.erb
- app/views/laws/_related_tab.html.erb
- app/views/tags/show.html.erb
- public/css/new_theme.css
Added fixes for Documents, Pricing content and various styles.
> UI hotfixes

- app/views/laws/show.html.erb
- app/views/layouts/_logged_navbar.html.erb
Fixed: 
"dpcumentos", "Adquiérelo" on modal
Added "Precios" section in dropdown
> Added fixes for modal and account dropdown

- app/views/billing/checkout.html.erb
Fixing typos and removing extra class to avoid misalignment.
> Added small adjustments for alignment in coupon line

- Gemfile
> [deps] Update to latest version of rails #217

- app/views/laws/_content.html.erb
Temporal fix for search results issue:
https://discord.com/channels/600740585887760385/715749457379196948/775184092941254707
> Quick TEMP fix for Search results article number link added

- app/javascript/packs/trim_articles_for_preview.js
- app/views/laws/_content.html.erb
> ignore Artículo Headding and don't change queries with accent when trimming

- app/views/home/_enterprise_pricing_description.html.erb
> Cambio Precio

- app/controllers/api/v1/documents_controller.rb
- app/helpers/application_helper.rb
Reverts TodoLegal/TodoLegal#348
> Revert "x"

- app/controllers/home_controller.rb
- test/integration/customize_highlight_test.rb
> highlight search term

- app/controllers/api/v1/documents_controller.rb
- app/models/document.rb
- test/fixtures/documents.yml
- test/models/document_test.rb
Order and remove nils from publication dates.
> Order publication date and remove nils

- app/controllers/api/v1/documents_controller.rb
- app/models/document.rb
Aims to improve data search by different date formats.
> search by date

- app/controllers/admin_controller.rb
- app/controllers/documents_controller.rb
- app/helpers/application_helper.rb
- app/jobs/users_download_job.rb
- app/mailers/users_download_mailer.rb
- app/views/users_download_mailer/send_csv_email.html.erb
- test/mailers/previews/document_processing_mailer_preview.rb
- test/mailers/previews/users_download_mailer_preview.rb
- test/mailers/users_download_mailer_test.rb
Send the users download action to a backgroun process
> Users download job

- app/controllers/api/v1/documents_controller.rb
- app/models/tag.rb
Aims to improve tags filtering.
> Fix documents tags and tags

- app/controllers/api/v1/documents_controller.rb
- app/models/document.rb
Aims to fix multiple tags search.
> Fixing multiple tags

- app/javascript/controllers/document_form_validator_controller.js
- app/views/documents/_edit_form.html.erb
> Fix: enhance document form validation to skip issue ID check for specific document types

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/users/registrations_controller.rb
- app/helpers/application_helper.rb
- app/views/devise/registrations/edit.html.erb
Reverts TodoLegal/TodoLegal#896
> Revert "Update stripe gem from version to 13.4.1"

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/users/registrations_controller.rb
- app/helpers/application_helper.rb
- app/views/devise/registrations/edit.html.erb
Reverts TodoLegal/TodoLegal#898
> Revert "Revert "Update stripe gem from version to 13.4.1""

- app/controllers/application_controller.rb
- app/controllers/home_controller.rb
- app/controllers/laws_controller.rb
- app/controllers/tags_controller.rb
- app/helpers/application_helper.rb
- app/models/law.rb
- app/views/home/_search_result.html.erb
- app/views/laws/_law_header.html.erb
Resolve n+1 queries and multiple unnecesary Stripe requests
> Laws search improvements

- app/controllers/application_controller.rb
There were not noticeable improvements after the implementation. It also added complexity to the code.
> revert back to one-phase search for articles
